### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by giovannicimolin** [geodesign/django-wms#4]
Hi @yellowcap! Is this still actively maintained? Would you accept PRs with fixes/upgrades?

**Comment by giovannicimolin** [comment]
It doesn't look like. :disappointed:

**Comment by yellowcap** [comment]
Hi sorry for not answering. I don't have much time to make updates myself, but if you want to make PRs those are most welcome

**Comment by giovannicimolin** [comment]
No problem! Thanks for the reply - I'm currently not using the library, but I'm considering it for a future project. I'll definitely push some PRs if I end up using it. :grin:

**Comment by yellowcap** [comment]
Nowadays I would also consider using other libraries that are more lightweight and based on [cloud optimized geotiff](https://www.cogeo.org/) rendering. For instance https://github.com/developmentseed/titiler
